# Generated by Django 5.1.7 on 2025-08-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_register',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
