# Generated by Django 5.1.7 on 2025-08-28 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_tbl_register_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_day_of_period', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration of period in days')),
                ('flow_intensity', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], max_length=10)),
                ('symptoms', models.TextField(blank=True, help_text='List symptoms like cramps, headache, etc.', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_inputs', to='userapp.tbl_register')),
            ],
        ),
    ]
