# Generated by Django 5.1.7 on 2025-08-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_cycleinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycleinput',
            name='flow_intensity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
