# Generated by Django 5.1.7 on 2025-08-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_cycleinput_flow_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleinput',
            name='average_cycle_length',
            field=models.IntegerField(blank=True, help_text='Average cycle length in days', null=True),
        ),
    ]
