# Generated by Django 5.1.7 on 2025-11-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0006_cart_cartpayment_productbooking_bookingpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
