# Generated by Django 5.2.10 on 2026-01-29 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0007_alter_cart_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_hospital_doctor_register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("experience", models.IntegerField(blank=True, null=True)),
                (
                    "hospital_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("hospital_address", models.TextField(blank=True, null=True)),
                (
                    "hospital_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("role", models.CharField(default="hospital_doctor", max_length=30)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("place", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital_doctor_images/"
                    ),
                ),
                (
                    "medical_id",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital_medical_ids/"
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalDoctorTimeSlotGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("timeslots", models.JSONField(blank=True, default=list)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_groups",
                        to="userapp.tbl_hospital_doctor_register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalDoctorFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_feedbacks",
                        to="userapp.tbl_register",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_feedbacks",
                        to="userapp.tbl_hospital_doctor_register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=20)),
                ("status", models.CharField(default="booked", max_length=20)),
                ("is_booked", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.tbl_register",
                    ),
                ),
                (
                    "timeslot_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.hospitaldoctortimeslotgroup",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="userapp.tbl_hospital_doctor_register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TblPredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(default=0)),
                ("weight", models.FloatField(default=0)),
                ("height", models.FloatField(default=0)),
                ("bmi", models.FloatField(default=0)),
                ("fast_food_consumption", models.CharField(default="0", max_length=50)),
                ("blood_group", models.CharField(default="Unknown", max_length=10)),
                ("cycle_regularity", models.CharField(default="0", max_length=50)),
                ("hair_growth", models.CharField(default="0", max_length=50)),
                ("acne", models.CharField(default="0", max_length=50)),
                ("mood_swings", models.CharField(default="0", max_length=50)),
                ("skin_darkening", models.CharField(default="0", max_length=50)),
                ("pdf_file", models.FileField(upload_to="medical_reports/")),
                ("result", models.CharField(default="Pending", max_length=50)),
                ("extracted_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.tbl_register",
                    ),
                ),
            ],
        ),
    ]
