# Generated by Django 5.2.10 on 2026-02-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_tbl_hospital_doctor_register_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_register',
            old_name='user_type',
            new_name='role',
        ),
    ]
