# Generated by Django 5.2.10 on 2026-02-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_rename_user_type_tbl_register_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_register',
            name='place',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
