# Generated by Django 5.2.10 on 2026-02-13 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_tbl_register_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctorfeedback',
            name='booking',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='userapp.hospitalbooking'),
            preserve_default=False,
        ),
    ]
